spring:
  datasource:
    url: jdbc:mysql://todolistdb.cnisharl1g3d.ap-northeast-2.rds.amazonaws.com:3306/todolistdb?serverTimezone=UTC
    username: todouser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
